# fly.toml app configuration file generated for bylinecms on 2025-07-22T12:44:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bylinecms'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
